-- 5
USE DATABASE LAPTOP_DWH;
USE SCHEMA STAGING;

-- COPY DATA FROM STAGE TO TABLE
COPY INTO STG_LAPTOPS
FROM @laptop_csv_stage
FILE_FORMAT = (FORMAT_NAME = laptops_csv_format);

SELECT COUNT(*)
FROM STG_LAPTOPS;

SELECT *
FROM STG_LAPTOPS
LIMIT 5;
