-- 2
USE DATABASE LAPTOP_DWH;
USE SCHEMA STAGING;

CREATE OR REPLACE FILE FORMAT laptops_csv_format
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE FILE FORMAT laptops_infer_format
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
PARSE_HEADER = TRUE;