-- 3
USE DATABASE LAPTOP_DWH;
USE SCHEMA STAGING;

-- TO CHECK IF THE FILE FORMAT(laptops_infer_format) WORKS PROPERLY, I.E. IF COLUMN NAMES FROM THE CSV ARE USED FOR THE COLUMNS NAMES OF THE TABLE AND TO CHECK DATA TYPES
SELECT *
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@laptop_csv_stage',
        FILE_FORMAT => 'laptops_infer_format'
    )
);

-- GENERATING COLUMN NAMES TO CREATE TABLE FROM STAGE
SELECT GENERATE_COLUMN_DESCRIPTION(
    ARRAY_AGG(OBJECT_CONSTRUCT(
        'COLUMN_NAME', COLUMN_NAME,
        'TYPE', TYPE,
        'NULLABLE', NULLABLE
    )) WITHIN GROUP (ORDER BY ORDER_ID),
    'table'
)
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@laptop_csv_stage',
        FILE_FORMAT => 'laptops_infer_format'
    )
);