-- 1
SHOW WAREHOUSES;

CREATE DATABASE IF NOT EXISTS LAPTOP_DWH;
USE DATABASE LAPTOP_DWH;
SELECT CURRENT_DATABASE();

CREATE SCHEMA IF NOT EXISTS STAGING;
USE SCHEMA STAGING;
SELECT CURRENT_SCHEMA();

-- Holds files before loading them into tables
CREATE STAGE IF NOT EXISTS laptop_csv_stage;
SHOW STAGES;
-----------------------------------
-- csv loaded into stage
-----------------------------------
LIST @laptop_csv_stage;

CREATE SCHEMA IF NOT EXISTS CURATED;
USE SCHEMA CURATED;

USE DATABASE LAPTOP_DWH;
USE SCHEMA STAGING;

USE DATABASE LAPTOP_DWH;
USE SCHEMA CURATED;